# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EVCSPlugin
                                 A QGIS plugin
 Estimates possible locations for EV Charging Stations given relevant data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-17
        copyright            : (C) 2025 by Vishesh, Aashuthosh, Sarthak
        email                : aashuthoshsadashivasharma@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Vishesh, Aashuthosh, Sarthak'
__date__ = '2025-11-17'
__copyright__ = '(C) 2025 by Vishesh, Aashuthosh, Sarthak'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EVCSPlugin class from file EVCSPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .evcs_plugin import EVCSPluginPlugin
    return EVCSPluginPlugin()
